# Generated by Django 4.1.4 on 2022-12-20 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aliases',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(db_index=True, max_length=50, verbose_name='Название категории (еда,жилье,тс, итд')),
                ('codename', models.CharField(db_index=True, max_length=50, verbose_name='Название раздела (Потребности|Инвестиции|Желания')),
                ('aliases_list', models.TextField(verbose_name='Список алиасов передается через -> : ')),
            ],
            options={
                'verbose_name': 'Алиасы',
                'verbose_name_plural': 'Алиасы',
            },
        ),
        migrations.CreateModel(
            name='Expenses_needs',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('codename', models.CharField(max_length=50, verbose_name='Название раздела (Потребности|Инвестиции|Желания')),
                ('category', models.CharField(max_length=50, verbose_name='Название категории (еда,жилье,тс, итд')),
                ('aliases', models.CharField(max_length=50, verbose_name='Название алиаса (магазин:продукты:итд')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('quantity', models.IntegerField(blank=True, null=True, verbose_name='Количество')),
                ('data_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('raw_text', models.TextField(verbose_name='Полный текст сообщения')),
            ],
            options={
                'verbose_name': 'Расходы',
                'verbose_name_plural': 'Расходы',
            },
        ),
        migrations.CreateModel(
            name='Purposes',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=15, verbose_name='ID пользователя из телеграма')),
                ('codename', models.CharField(max_length=50, verbose_name='Название раздела (Потребности|Инвестиции|Желания')),
                ('category', models.CharField(max_length=50, verbose_name='Название категории (еда,жилье,тс, итд')),
                ('aliases', models.CharField(max_length=50, verbose_name='Название алиаса (магазин:продукты:итд')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('data', models.CharField(max_length=15, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Цели',
                'verbose_name_plural': 'Цели',
            },
        ),
        migrations.CreateModel(
            name='User_verification',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=50, verbose_name='ID пользователя из телеграма')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='Имя пользователя из телеграма')),
                ('activating_bot', models.CharField(max_length=50, verbose_name='Активация бота: True - есть цели, False - нет целей')),
            ],
            options={
                'verbose_name': 'Аутентификации пользователя',
                'verbose_name_plural': 'Аутентификации пользователя',
            },
        ),
    ]
